version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: student-crud
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student
    volumes:
      - db:/var/lib/mysql


volumes:
  db: