version: '3.8'

services:
  mysql-custom:
    image: mysql:latest
    container_name: mysql-crud
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student
    volumes:
      - db:/var/lib/mysql

  my-app:
    image: student-crud
    container_name: student-docker
    ports:
      - '8087:8089'
    depends_on:
      - mysql-custom
    restart: always


volumes:
  db: